# ???? ??????? (?????? ????????? ? ??????????? ? SonarCloud)
sonar.projectKey=abominate-sloth_Practic
sonar.projectName=Practic (Angular Frontend)

# ???? ? ??????????
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# ???? ? ????????? TypeScript
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# ?????????? ???????? ??????
sonar.exclusions=**/node_modules/**, **/*.html
