sonar.projectKey=abominate-sloth_Practic_React
sonar.projectName=Practic (React Frontend)
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.css,**/*.svg
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx