sonar.projectKey=adeptsofsloth_Practic
sonar.projectName=Practic
sonar.organization=adeptsofsloth
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.coverage.exclusions=**/*

