name: SonarCloud (Angular)
on:
  push:
    branches: [front_angular]
  pull_request:
    branches: [front_angular]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Пропускаем тесты, просто собираем проект
      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
